version: "3.7"

services:
  database:
    image: mongo:latest
    container_name: dbmongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
        - "27017:27017"
    volumes:
      - /data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@database:27017/